generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Product
    theme:            default
    css:             /sf/sf_admin/css/admin_main.css

    edit:
      title: Create/Edit Product
      display: [name, price, description, initial_balance , registration_fee,include_in_zerocall, is_in_store,is_in_b2b, country_id,sms_code, product_order,billing_product_id,product_type_id,bonus]
 
      fields:
              enablecountry: {name: Country}
              include_in_zerocall: {name: Customer Module}
              is_in_store: {name: Agent Module}
              is_reg_share_value_pc: {name: Is Reg. share value %}
              is_extra_payments_share_value_pc: {name: Is extra refill share value %}
    list:
      display: [name,  price, registration_fee, total_amount, description, initial_balance, bonus, net_balance_given  , include_in_zerocall, is_in_store,is_in_b2b, enablecountry, sms_code, product_order,billing_products,product_type]
      fields:
              enablecountry: {name: Country}
              include_in_zerocall: {name: Customer Module}
              is_in_store: {name: Agent Module}
      max_per_page: 100
      object_actions:
        _edit: ~
        _delete: ~

    fields:
      name:     { name: Product Name }
      refill_options:   { help: Refill Amount Must be Comma Separate }
      is_reg_share_value_pc: {name: Is Reg. share value %}
      is_extra_payments_share_value_pc: {name: Is extra refill share value %}