default:
  http_metas:
    content-type: text/html

  metas:
    title:         Kimarin - Agent Portal
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css, style.css, 960.css]

  javascripts:    []

  has_layout:     on
  layout:         layout
